"""db creation

Revision ID: 427f40f90754
Revises: 
Create Date: 2023-07-04 09:29:25.759386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '427f40f90754'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
